name: baytech
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.8
  dtd: ^4.0.0
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.3.3
  http: ^1.6.0
  image_picker: ^1.2.1
  json_rpc_2: ^4.0.0
  lottie: ^3.3.2
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.1
  photo_view: ^0.15.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  stack_trace: ^1.12.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  web: ^1.1.1
  flutter_localizations:
        sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo black.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/images/team/
    - assets/fonts/

  fonts:
    - family: Platypi
      fonts:
        - asset: assets/fonts/Platypi-VariableFont_wght.ttf
flutter_intl:
  enabled: true
